apiVersion: 1

datasources:
  - name: InfluxDB-Datenkrake
    uid: influx-datenkrake
    type: influxdb
    access: proxy
    url: http://historian:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: datenkrake
      defaultBucket: telemetrie
      tlsSkipVerify: true
    secureJsonData:
      token: changeMeHistorianToken
